import { useState } from 'react'
import { Save, Cog, Wallet, HardDrive, CheckCircle2 } from 'lucide-react'
import { useConnection } from '../../context/ConnectionContext'
import { useToast } from '../../context/ToastContext'
import { normalizeEndpoint } from '../../config'
import ColabSetup from './ColabSetup'

export default function ConnectionSettings() {
  const { endpoint, saveEndpoint, testConnection, checking, status, connectionInfo } = useConnection()
  const toast = useToast()
  const [draft, setDraft] = useState(endpoint)

  function handleSave() {
    const normalized = saveEndpoint(draft)
    toast.success('Endpoint saved')
    setDraft(normalized)
  }

  async function handleTest() {
    const target = draft.trim() || endpoint
    if (!target) {
      toast.error('Enter an API endpoint first.')
      return
    }
    const res = await testConnection(target)
    if (res.connected) {
      toast.success('Connection successful')
    } else {
      toast.error(res.error?.friendly || 'Connection failed')
    }
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <ColabSetup />

      <div className="glass-card p-6 rounded-xl space-y-4">
        <div className="flex items-center gap-2 text-sm font-semibold text-white mb-4">
          <Cog className="w-4 h-4 text-accent" /> AI CONNECTION
        </div>

        <div className="grid grid-cols-3 gap-3 text-center">
          <div className="bg-dark-800 rounded-lg p-3 border border-dark-700/50">
            <div className="text-[10px] uppercase tracking-wider text-dark-500 mb-1">Engine</div>
            <div className="text-sm font-medium text-white flex items-center justify-center gap-1.5">
              <Wallet className="w-3.5 h-3.5 text-accent" /> Ollama
            </div>
          </div>
          <div className="bg-dark-800 rounded-lg p-3 border border-dark-700/50">
            <div className="text-[10px] uppercase tracking-wider text-dark-500 mb-1">Model</div>
            <div className="text-sm font-medium text-white">Gemma 3 12B</div>
          </div>
          <div className="bg-dark-800 rounded-lg p-3 border border-dark-700/50">
            <div className="text-[10px] uppercase tracking-wider text-dark-500 mb-1">GPU</div>
            <div className="text-sm font-medium text-white flex items-center justify-center gap-1.5">
              <HardDrive className="w-3.5 h-3.5 text-accent" /> NVIDIA T4
            </div>
          </div>
        </div>

        <div>
          <label htmlFor="endpoint" className="block text-xs font-semibold uppercase tracking-wider text-dark-400 mb-2">
            API Endpoint
          </label>
          <input
            id="endpoint"
            type="url"
            value={draft}
            onChange={e => setDraft(e.target.value)}
            placeholder="https://xxxxx.trycloudflare.com"
            className="input-field"
            autoComplete="url"
          />
          <p className="mt-2 text-xs text-dark-500">
            The temporary Cloudflare endpoint generated by your Colab server.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-2">
          <button onClick={handleSave} className="btn-primary flex-1">
            <Save className="w-4 h-4" /> Save Endpoint
          </button>
          <button onClick={handleTest} disabled={checking} className="btn-secondary flex-1">
            {checking ? (
              <><span className="w-4 h-4 border-2 border-dark-400 border-t-transparent rounded-full animate-spin" /> Testing...</>
            ) : (
              <>Test Connection</>
            )}
          </button>
        </div>

        <div className="border-t border-dark-800 pt-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-dark-400">Status</span>
            {checking && <span className="text-xs text-dark-400 animate-pulse">Checking...</span>}
          </div>

          {status === 'connected' && connectionInfo && (
            <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-lg p-4 space-y-2 animate-fade-in">
              <div className="flex items-center gap-2 text-emerald-400 text-sm font-medium">
                <CheckCircle2 className="w-4 h-4" /> Connection Successful
              </div>
              <div className="grid grid-cols-2 gap-2 text-xs text-dark-300">
                <div className="flex justify-between"><span className="text-dark-500">AI Server</span><span className="text-emerald-400">Online</span></div>
                <div className="flex justify-between"><span className="text-dark-500">Ollama</span><span className={connectionInfo.ollama ? 'text-emerald-400' : 'text-rose-400'}>{connectionInfo.ollama ? 'Online' : 'Offline'}</span></div>
                <div className="flex justify-between"><span className="text-dark-500">Vision Model</span><span className="text-dark-200">Gemma 3 12B</span></div>
                <div className="flex justify-between"><span className="text-dark-500">GPU</span><span className="text-dark-200">NVIDIA T4</span></div>
              </div>
            </div>
          )}

          {status === 'error' && connectionInfo && (
            <div className="bg-rose-500/5 border border-rose-500/20 rounded-lg p-4 space-y-3 animate-fade-in">
              <div className="flex items-center gap-2 text-rose-400 text-sm font-medium">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"/></svg>
                Connection Failed
              </div>
              <p className="text-xs text-dark-300">{connectionInfo.friendly}</p>
              <p className="text-xs text-dark-500">
                Please make sure:
                <br />1. Colab is running
                <br />2. T4 GPU is enabled
                <br />3. Notebook was executed
                <br />4. API endpoint is correct
              </p>
              <div className="flex gap-2">
                <button onClick={handleTest} disabled={checking} className="btn-secondary flex-1 text-xs">
                  <RefreshIcon spin={checking} /> Retry
                </button>
              </div>
            </div>
          )}

          {status === 'idle' && (
            <p className="text-xs text-dark-500">Save an endpoint and test the connection.</p>
          )}
          {status === 'checking' && (
            <p className="text-xs text-dark-500 animate-pulse">Testing connection to your Colab server...</p>
          )}
        </div>
      </div>
    </div>
  )
}

function RefreshIcon({ spin }) {
  return (
    <svg className={`w-4 h-4 ${spin ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
    </svg>
  )
}
